# action.yml
name: 'Test Tripal Action'
description: 'Run automated testing for a Tripal extension module.'
inputs:
  directory-name:
    description: "The name of the directory your Tripal module or package was checked out into."
    required: true
  modules:
    description: "A space-separated list of module machine names indicating which modules to install before running tests."
    required: true
  php-version:
    description: "The version of PHP you would like tested. This must match one of the current PHP versions TripalDocker is available in (e.g. 8.3)."
    required: false
    default: '8.3'
  pgsql-version:
    description: "The version of PostgreSQL you would like your tests run against. This must match one of the current versions TripalDocker is available in (e.g. 13, 16)."
    required: false
    default: '16'
  drupal-version:
    description: "The version of Drupal you would like your tests run against. This must match one of the current versions TripalDocker is available in (e.g. 11.1.x-dev)."
    required: false
    default: '11.1.x-dev'
  phpunit-config:
   description: "The phpunit.xml file to configure the tests. If left blank, we will try to locate it using the following patters: (1) phpunit.VER.xml (where VER is 9 for drupal 10.4/5; 10 for drupal 11.1; 11 for drupal 11.2+), (2) phpunit.xml"
   required: false
  phpunit-command-options:
    description: "A string providing any options you would like added to the phpunit command."
    required: false
    default: ' '
  qltycloud-reporter-id:
    description: the reporter ID for QLTY Cloud to publish results to. This should be saved as a secret in your repository.
    required: false
  build-image:
    description: "Indicates whether you would like to build the docker based on your code (true) or pull an existing image (false)."
    required: true
    default: 'false'
  dockerfile:
    description: "The relative path and file name for the dockerfile to use with build-image."
    required: true
    default: 'Dockerfile'
outputs:
  config_file:
    description: 'The filename of the phpunit.xml configuration file to use.'
    value: ${{ steps.detect-phpunit-config.outputs.config_file }}
runs:
  using: "composite"
  steps:
      # Here we pull the development tripaldocker image for this combo
      - name: Pull TripalDocker Image
        if: ${{ inputs.build-image == 'false' }}
        shell: bash
        env:
          IMAGE_TAG: "drupal${{ inputs.drupal-version }}-php${{ inputs.php-version }}-pgsql${{ inputs.pgsql-version }}"
        run: |
          docker pull tripalproject/tripaldocker:$IMAGE_TAG
          docker image tag tripalproject/tripaldocker:$IMAGE_TAG testing:localdocker
      - name: Build Local Docker Image
        if: ${{ inputs.build-image == 'true' }}
        shell: bash
        run: |
            docker build --tag=testing:localdocker \
              --build-arg drupalversion="${{ inputs.drupal-version }}" \
              --build-arg phpversion="${{ inputs.php-version }}" \
              --build-arg postgresqlversion="${{ inputs.pgsql-version }}" \
              --build-arg chadoschema='teacup' ./
      # Just spin up docker the good ol' fashion way
      # mounting our currently checked out package inside the docker container.
      - name: Spin up Docker locally
        shell: bash
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal/web/modules/contrib/${{ inputs.directory-name }} testing:localdocker
          docker exec tripaldocker bash -c "until pg_isready --dbname=sitedb --username=drupaladmin --host=localhost; do sleep 1; done"
      # Install the modules
      - name: Install our package in Docker
        if: "${{ inputs.modules != '' }}"
        shell: bash
        run: |
          docker exec tripaldocker drush en ${{ inputs.modules }} --yes
      # Detect the PHPUnit config based on Drupal version.
      - id: 'detect-phpunit-config'
        name: "Detect version of phpunit"
        if: "${{ inputs.phpunit-config == '' }}"
        shell: bash
        run: |
          config_file='phpunit.xml'
          version_str=$(docker exec --workdir=/var/www/drupal/web/modules/contrib/${{ inputs.directory-name }} tripaldocker phpunit --version)
          major_version=$(echo "$version_str" | sed -E 's/^PHPUnit ([0-9]+).*/\1/')
          if [ -n "$major_version" ]; then
              versioned_file="phpunit.${major_version}.xml"
              if [ -f "$versioned_file" ]; then
                  config_file="$versioned_file"
              else
                echo "We checked for $versioned_file but it didn't exist."
              fi
          fi
          echo "Using phpunit config file: $config_file"
          echo "config_file=$config_file" >> $GITHUB_OUTPUT
      # Runs the PHPUnit tests without coverage.
      - name: Run PHPUnit Tests
        if: "${{ inputs.qltycloud-reporter-id == '' }}"
        shell: bash
        run: |
          docker exec --workdir=/var/www/drupal/web/modules/contrib/${{ inputs.directory-name }} tripaldocker phpunit --version
          echo "Previously we detected that we should use ${{ steps.detect-phpunit-config.outputs.config_value }}"
          docker exec \
            --workdir=/var/www/drupal/web/modules/contrib/${{ inputs.directory-name }} \
            tripaldocker phpunit ${{ inputs.phpunit-command-options }}
      # Runs the PHPUnit tests WITH coverage.
      - name: Run PHPUnit Tests with coverage for QLTY Cloud
        if: "${{ inputs.qltycloud-reporter-id != '' }}"
        shell: bash
        env:
          COVERAGE_REPORT: "/var/www/drupal/web/modules/contrib/${{ inputs.directory-name }}/clover.xml"
        run: |
          docker exec \
            --workdir=/var/www/drupal/web/modules/contrib/${{ inputs.directory-name }} \
            tripaldocker phpunit ${{ inputs.phpunit-command-options }} \
            --coverage-text --coverage-clover $COVERAGE_REPORT
          ls
      # Publish to QLTY Cloud
      - name: Publish code coverage to QLTY Cloud
        if: "${{ inputs.qltycloud-reporter-id != '' }}"
        uses: 'qltysh/qlty-action/coverage@v1'
        with:
          token: '${{ inputs.qltycloud-reporter-id }}'
          files: "clover.xml"
          strip-prefix: "/var/www/drupal/web/modules/contrib/${{ inputs.directory-name }}"
