name: 'Single Version Combo'

on:
  push:
  workflow_dispatch:

jobs:
  test_all_defaults:
    name: "Only Required Options"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
        - id: tripal/tripal
          directory: tripal
          filter: testTripalAdminPages
        - id: TripalCultivate/TripalCultivate
          directory: TripalCultivate
          filter: testPreprocessPage
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone Repo for testing purposes
        run: |
          git clone https://github.com/${{ matrix.repo.id }}.git tmp
          cd tmp
          git checkout 4.x
          mv * ../
          ls ../
      - name: Run the action step
        uses: ./ # Uses an action in the root directory
        with:
          directory-name: ${{ matrix.repo.directory }}
          phpunit-command-options: "--filter ${{ matrix.repo.filter }}"
  test_all_provided:
    name: "Specify versions + build docker"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
        - id: tripal/tripal
          directory: tripal
          filter: testTripalAdminPages
        - id: TripalCultivate/TripalCultivate
          directory: TripalCultivate
          filter: testPreprocessPage
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone Tripal for testing purposes
        run: |
          git clone https://github.com/${{ matrix.repo.id }}.git tmp
          cd tmp
          git checkout 4.x
          mv * ../
          ls ../
      - name: Run the action step
        uses: ./ # Uses an action in the root directory
        with:
          directory-name: ${{ matrix.repo.directory }}
          phpunit-command-options: "--filter ${{ matrix.repo.filter }}"
          php-version: "8.4"
          pgsql-version: "18"
          drupal-version: "11.2.x-dev"
          build-image: true
          dockerfile: "Dockerfile"
  test_qltycloud:
    name: "QltyCloud coverage reporting"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
        - id: tripal/tripal
          directory: tripal
          filter: testTripalAdminPages
        - id: TripalCultivate/TripalCultivate
          directory: TripalCultivate
          filter: testPreprocessPage
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Clone Tripal for testing purposes
        run: |
          git clone https://github.com/${{ matrix.repo.id }}.git tmp
          cd tmp
          git checkout 4.x
          mv * ../
          ls ../
      - name: Run the action step
        uses: ./ # Uses an action in the root directory
        with:
          directory-name: ${{ matrix.repo.directory }}
          phpunit-command-options: "--filter ${{ matrix.repo.filter }}"
          qltycloud-reporter-id: ${{ secrets.QLTY_COVERAGE_TOKEN }}
