name: 'Matrixed'

on:
  push:
  workflow_dispatch:

jobs:
  test_all_provided:
    name: "Basic"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
        - id: tripal/tripal
          directory: tripal
          filter: testTripalAdminPages
#        - id: TripalCultivate/TripalCultivate
#          directory: TripalCultivate
#          filter: testPreprocessPage
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'
        pgsql-version:
          - '18'
        drupal-version:
          - '10.6.x'
          - '11.3.x'
          - '11.4.x'
          - '11.x-dev'
        exclude:
        exclude:
          # Only Drupal 11.3+ supports PHP 8.5
          - php-version: '8.5'
            drupal-version: '10.6.x'
          # Drupal 11+ requires PHP 8.3+
          - php-version: '8.2'
            drupal-version: '11.3.x'
          - php-version: '8.2'
            drupal-version: '11.4.x'
          - php-version: '8.2'
            drupal-version: '11.x-dev'
          # Drupal 11.x is the bleeding edge so only run it on the latest php.
          - php-version: '8.2'
            drupal-version: '11.x-dev'
          - php-version: '8.3'
            drupal-version: '11.x-dev'
          - php-version: '8.4'
            drupal-version: '11.x-dev'
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v6
      - name: Clone Tripal for testing purposes
        run: |
          git clone https://github.com/${{ matrix.repo.id }}.git tmp
          cd tmp
          git checkout 4.x
          mv * ../
          ls ../
      - name: Run the action step
        uses: ./ # Uses an action in the root directory
        with:
          directory-name: ${{ matrix.repo.directory }}
          phpunit-command-options: "--filter ${{ matrix.repo.filter }}"
          php-version: ${{ matrix.php-version }}
          pgsql-version: ${{ matrix.pgsql-version }}
          drupal-version: ${{ matrix.drupal-version }}
          build-image: true
          dockerfile: "Dockerfile"
